folders:
  dataset: "/Users/dhresko/Documents/Trajectories/movementLogs"
  test_raw: "/Users/dhresko/Documents/Trajectories/generated/raw"
  test_heatmaps: "/Users/dhresko/Documents/Trajectories/generated/samples"
  training_logs: "/Users/dhresko/Documents/Trajectories/training"